### PR TITLE
Set up CI

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref DEV-1320

### CODE REVIEW

**Comment by louischan-oursky** [comment]
No GitHub Actions workflow was run

**Comment by tung2744** [comment]
@louischan-oursky Is this pr completed? Seems no checks are running for this pr, or this pr needs to be merged first to trigger ci in later prs?

**Comment by louischan-oursky** [comment]
It is complete. But I have no idea why no actions were run.

**Comment by louischan-oursky** [comment]
Let's merge this first and see if the actions will be run?

**Pull request merged**
